title: My Awesome Blog
author: Kristoffherson Flores
email: kristoffhersonflores@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description of my blog
theme: minima

# social links
twitter_username: ktoffher # DO NOT include the @ character, or else the build will fail!
github_username:  krist0fffff # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
